made descriptions optional
ucsb-cs156-f24/proj-courses-f24-02 pull request #15
Opened 2024-11-17 00:32 UTC by billybobjoe123

#11 
made descriptions optional in form and controller. edited frontend form test to not require description.

2024-11-17 01:42 UTC, berdly commented
Looks good mostly although there's a few things I'm noticing: 

- It's redundant to set required to false on the `RequestParam` annotation since the argument is now an `Optional<T>` it's like putting `Optional<Optional<T>>`. You should probably remove the `required=false` bit since Spring 'understands' what we're trying to say with the typing alone.

- Since `PersonalSchedule.description` is always optional now, we should consider changing this variable's type to `Optional<String>` instead of simply making it empty when there's no value. That would probably need to be it's own issue though since it would require changes in a decent amount of places. If anyone with authority who's reading this could weigh in, I'd be interested to see if that would be considered a contribution worth points

2024-11-17 03:42 UTC, berdly commented
Sorry but the `RequestParam` annotation is still needed, just not the `(required = false)` part.

2024-11-17 03:48 UTC, berdly approved these changes

2024-11-19 22:23 UTC, pconrad requested changes
Apart from the [commented out code](https://ucsb-cs156.github.io/topics/code_reviews/commented_out_code.html#why-should-commented-out-code-be-removed) LGTM.  Fix that and then it's mergeable.

2024-11-19 22:23 UTC, pconrad commented on frontend/src/tests/components/PersonalSchedules/PersonalScheduleForm.test.js
> +    //expect(screen.getByText(/Description is required./)).toBeInTheDocument();    no longer necessary due to issue #11 making descriptions optional
Please do not leave commented out code in the PR.  Remove it.  

Here's why:
https://ucsb-cs156.github.io/topics/code_reviews/commented_out_code.html#why-should-commented-out-code-be-removed

2024-11-21 08:21 UTC, billybobjoe123 commented
deployment link:
https://proj-courses-dev-billybobjoe123.dokku-02.cs.ucsb.edu/

2024-11-21 23:55 UTC, pconrad approved these changes
LGTM

2024-11-21 23:56 UTC, merged