completed finals info backend, including test cases
ucsb-cs156-f24/proj-courses-f24-02 pull request #35
Opened 2024-11-25 21:47 UTC by leozhu0

2024-11-26 02:10 UTC, berdly requested changes

2024-11-26 02:10 UTC, berdly commented on src/main/java/edu/ucsb/cs156/courses/services/UCSBCurriculumService.java
> +    HttpStatus statusCode = null;
```suggestion
    String retVal;
    MediaType contentType;
    HttpStatus statusCode;
```
Since these get immediately provided real values shortly afterward anyway, it doesn't make sense to give these fallback values like this. Leaving them declared but uninitialized is safer since it will provide a compile time warning if they are used before being provided their proper values.

2024-11-26 02:11 UTC, berdly commented on src/main/java/edu/ucsb/cs156/courses/services/UCSBCurriculumService.java
> +    HttpStatus statusCode = null;
Otherwise LGM!

2024-11-26 02:17 UTC, leozhu0 commented on src/main/java/edu/ucsb/cs156/courses/services/UCSBCurriculumService.java
> +    HttpStatus statusCode = null;
Added your suggestion!

2024-11-26 02:19 UTC, berdly approved these changes, later dismissed

2024-11-26 16:37 UTC, pconrad submitted a review, later dismissed
LGTM!  will test on dokku

2024-11-26 16:41 UTC, pconrad commented
Having trouble with testing:

<img width="467" alt="image" src="https://github.com/user-attachments/assets/8d854651-3000-42dd-ab4e-0faa86b946d8">

2024-11-27 22:58 UTC, pconrad commented
closing because marked `wontfix` by the author.

2024-11-27 22:58 UTC, closed without merging